import math
help(math.ceil)
help(math.fabs)
help(math.log)
help(math.log10)
help(math.radians)
help(math.degrees)
help(math.pow)
help(math.exp)
help(abs)
print(abs(-5.4))
print(round(-24.9))
help(divmod)
print(divmod(5,2))
print(math.fabs(-23.2))